language: android

android:
  components:
    - build-tools-23.0.1
    - android-23
    - extra-android-m2repository
    - sys-img-armeabi-v7a-android-15

before_script:
  - cp gradle.properties.sample gradle.properties

jdk:
  - oraclejdk8

branches:
  except:
    - gh-pages

sudo: false

cache:
  directories:
    - $HOME/.gradle
